name: bbs

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  windows:
    name: windows / ${{ matrix.config }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - default

    steps:
      - uses: actions/checkout@v4

      - name: Checkout bbs
        uses: actions/checkout@v4
        with:
          repository: luppichristian/bbs
          path: .bbs-bootstrap

      - name: Build bbs (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Build bbs (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Init toolchain (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe update --init-toolchain

      - name: Init toolchain (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs update --init-toolchain

      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe build -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Build project (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs build -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe test -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs test -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe run -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs run -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe dist -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs dist -t * -p windows-x86_64 -c ${{ matrix.config }}

      - name: Upload windows dist (windows-x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: dist-windows-${{ matrix.config }}-windows-x86_64
          path: dist/${{ matrix.config }}-windows-x86_64

  linux:
    name: linux / ${{ matrix.config }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - default

    steps:
      - uses: actions/checkout@v4

      - name: Checkout bbs
        uses: actions/checkout@v4
        with:
          repository: luppichristian/bbs
          path: .bbs-bootstrap

      - name: Build bbs (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Build bbs (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Init toolchain (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe update --init-toolchain

      - name: Init toolchain (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs update --init-toolchain

      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe build -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Build project (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs build -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe test -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs test -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe run -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs run -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe dist -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs dist -t * -p linux-x86_64 -c ${{ matrix.config }}

      - name: Upload linux dist (linux-x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux-${{ matrix.config }}-linux-x86_64
          path: dist/${{ matrix.config }}-linux-x86_64

  macos:
    name: macos / ${{ matrix.config }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - debug
          - default

    steps:
      - uses: actions/checkout@v4

      - name: Checkout bbs
        uses: actions/checkout@v4
        with:
          repository: luppichristian/bbs
          path: .bbs-bootstrap

      - name: Build bbs (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Build bbs (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cmake -S .bbs-bootstrap -B .bbs-bootstrap/build
          cmake --build .bbs-bootstrap/build --config Release

      - name: Init toolchain (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe update --init-toolchain

      - name: Init toolchain (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs update --init-toolchain

      - name: Build project (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe build -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Build project (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs build -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe test -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Run tests (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs test -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe run -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Run targets (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs run -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          ./.bbs-bootstrap/build/bbs.exe dist -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Create distributions (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          ./.bbs-bootstrap/build/bbs dist -t * -p macos-x86_64 -c ${{ matrix.config }}

      - name: Upload macos dist (macos-x86_64)
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos-${{ matrix.config }}-macos-x86_64
          path: dist/${{ matrix.config }}-macos-x86_64

