#pragma once

#include "bbs_cmd.h"

#define DEF_BUILD_DIR "build"
#define DEF_DIST_DIR  "dist"

typedef bbs_gen user_gen;
typedef bbs_user_attr user_attr;
typedef bbs_user_text_attr user_text_attr;
typedef bbs_user_uint_attr user_uint_attr;
typedef bbs_user_attr_kind user_attr_kind;
typedef bbs_user_attr_info user_attr_info;
typedef bbs_user_gen_attr_info user_gen_attr_info;
typedef bbs_user user;

#define USER_ATTR_BUILDDIR BBS_USER_ATTR_BUILD_DIR
#define USER_ATTR_DISTDIR BBS_USER_ATTR_DIST_DIR
#define USER_ATTR_AUTO_DEBOUNCE_MS BBS_USER_ATTR_AUTO_DEBOUNCE_MS
#define USER_ATTR_AUTO_RETRY_COUNT BBS_USER_ATTR_AUTO_RETRY_COUNT
#define USER_ATTR_AUTO_RETRY_DELAY_MS BBS_USER_ATTR_AUTO_RETRY_DELAY_MS
#define USER_ATTR_DIST_ARCHIVE_FORMAT BBS_USER_ATTR_DIST_ARCHIVE_FORMAT
#define USER_ATTR_DIST_ARCHIVE_NAME BBS_USER_ATTR_DIST_ARCHIVE_NAME
#define USER_ATTR_CMAKE_ARGS BBS_USER_ATTR_CMAKE_ARGS
#define USER_ATTR_CMAKE_BUILD_ARGS BBS_USER_ATTR_CMAKE_BUILD_ARGS
#define USER_ATTR_CTEST_ARGS BBS_USER_ATTR_CTEST_ARGS
#define USER_ATTR_GEN BBS_USER_ATTR_GEN

#define USER_TEXT_BUILDDIR BBS_USER_TEXT_BUILD_DIR
#define USER_TEXT_DISTDIR BBS_USER_TEXT_DIST_DIR
#define USER_TEXT_DIST_ARCHIVE_FORMAT BBS_USER_TEXT_DIST_ARCHIVE_FORMAT
#define USER_TEXT_DIST_ARCHIVE_NAME BBS_USER_TEXT_DIST_ARCHIVE_NAME
#define USER_TEXT_CMAKE_ARGS BBS_USER_TEXT_CMAKE_ARGS
#define USER_TEXT_CMAKE_BUILD_ARGS BBS_USER_TEXT_CMAKE_BUILD_ARGS
#define USER_TEXT_CTEST_ARGS BBS_USER_TEXT_CTEST_ARGS
#define USER_TEXT_MAX BBS_USER_TEXT_MAX

#define USER_UINT_AUTO_DEBOUNCE_MS BBS_USER_UINT_AUTO_DEBOUNCE_MS
#define USER_UINT_AUTO_RETRY_COUNT BBS_USER_UINT_AUTO_RETRY_COUNT
#define USER_UINT_AUTO_RETRY_DELAY_MS BBS_USER_UINT_AUTO_RETRY_DELAY_MS
#define USER_UINT_MAX BBS_USER_UINT_MAX

#define USER_ATTR_KIND_TEXT BBS_USER_ATTR_KIND_TEXT
#define USER_ATTR_KIND_UINT BBS_USER_ATTR_KIND_UINT
#define USER_ATTR_KIND_ARCHIVE_FORMAT BBS_USER_ATTR_KIND_ARCHIVE_FORMAT
#define USER_ATTR_KIND_SECTION BBS_USER_ATTR_KIND_SECTION

#define USER_ATTR_INFOS BBS_USER_ATTR_INFOS
#define USER_GEN_ATTR_INFOS BBS_USER_GEN_ATTR_INFOS

static inline const char* user_text(const user* u, user_text_attr attr) {
  return bbs_user_text(u, attr);
}

static inline unsigned int user_uint(const user* u, user_uint_attr attr) {
  return bbs_user_uint(u, attr);
}
