#pragma once
#include "bbs_base.h"
#include "bbs_toolchain.h"
#include "bbs_config.h"

typedef bbs_meta meta;
typedef bbs_target_type target_type;
typedef bbs_lang lang;
typedef bbs_stdlib stdlib;
typedef bbs_warning_level warning_level;
typedef bbs_opt_level opt_level;
typedef bbs_package_source package_source;
typedef bbs_package_backend package_backend;
typedef bbs_unity_batch target_unity_batch;
typedef bbs_hook_kind target_hook_kind;
typedef bbs_hook_info target_hook_info;
typedef bbs_dist target_dist_config;
typedef bbs_project_attr_info project_attr_info;
typedef bbs_project_target_type_alias project_target_type_alias;
typedef bbs_project_lang_alias project_lang_alias;
typedef bbs_project_stdlib_alias project_stdlib_alias;
typedef bbs_project_warning_level_alias project_warning_level_alias;
typedef bbs_project_opt_level_alias project_opt_level_alias;
typedef bbs_project_cmake_config_alias project_cmake_config_alias;
typedef bbs_tgt target;
typedef bbs_builder builder;
typedef bbs_proj project;

#define TARGET_TYPE_CONSOLE BBS_TARGET_CONSOLE
#define TARGET_TYPE_CONSOLELESS BBS_TARGET_CONSOLELESS
#define TARGET_TYPE_HEADER_LIB BBS_TARGET_HEADER_LIB
#define TARGET_TYPE_STATIC_LIB BBS_TARGET_STATIC_LIB
#define TARGET_TYPE_DYN_LIB BBS_TARGET_DYN_LIB
#define TARGET_TYPE_OBJ_LIB BBS_TARGET_OBJ_LIB
#define TARGET_TYPE_TEST BBS_TARGET_TEST
#define TARGET_TYPE_DRIVER BBS_TARGET_DRIVER

#define LANG_C BBS_LANG_C
#define LANG_CPP BBS_LANG_CPP
#define LANG_CUDA BBS_LANG_CUDA

#define STDLIB_NONE BBS_STDLIB_NONE
#define STDLIB_DYNAMIC BBS_STDLIB_DYNAMIC
#define STDLIB_STATIC BBS_STDLIB_STATIC

#define WARNING_LEVEL_DEFAULT BBS_WARNING_DEFAULT
#define WARNING_LEVEL_NONE BBS_WARNING_NONE
#define WARNING_LEVEL_LOW BBS_WARNING_LOW
#define WARNING_LEVEL_MEDIUM BBS_WARNING_MEDIUM
#define WARNING_LEVEL_HIGH BBS_WARNING_HIGH
#define WARNING_LEVEL_PEDANTIC BBS_WARNING_PEDANTIC

#define OPT_LEVEL_DEFAULT BBS_OPT_DEFAULT
#define OPT_LEVEL_NONE BBS_OPT_NONE
#define OPT_LEVEL_DEBUG BBS_OPT_DEBUG
#define OPT_LEVEL_SIZE BBS_OPT_SIZE
#define OPT_LEVEL_SPEED_1 BBS_OPT_SPEED_1
#define OPT_LEVEL_SPEED_2 BBS_OPT_SPEED_2
#define OPT_LEVEL_SPEED_3 BBS_OPT_SPEED_3
#define OPT_LEVEL_AGGRESSIVE BBS_OPT_AGGRESSIVE

#define PACKAGE_SOURCE_NONE BBS_PACKAGE_NONE
#define PACKAGE_SOURCE_PATH BBS_PACKAGE_PATH
#define PACKAGE_SOURCE_REPO BBS_PACKAGE_REPO
#define PACKAGE_SOURCE_ARCHIVE BBS_PACKAGE_ARCHIVE

#define PACKAGE_BACKEND_NONE BBS_PACKAGE_BACKEND_NONE
#define PACKAGE_BACKEND_CMAKE BBS_PACKAGE_BACKEND_CMAKE
#define PACKAGE_BACKEND_BBS BBS_PACKAGE_BACKEND_BBS

#define TARGET_HOOK_POST_BUILD BBS_HOOK_POST_BUILD
#define TARGET_HOOK_PRE_BUILD BBS_HOOK_PRE_BUILD
#define TARGET_HOOK_PRE_RUN BBS_HOOK_PRE_RUN
#define TARGET_HOOK_POST_RUN BBS_HOOK_POST_RUN
#define TARGET_HOOK_PRE_DIST BBS_HOOK_PRE_DIST
#define TARGET_HOOK_POST_DIST BBS_HOOK_POST_DIST
#define TARGET_HOOK_MAX BBS_HOOK_MAX

#define TARGET_HOOK_INFOS BBS_HOOK_INFOS

#define PROJECT_TARGET_TYPE_ALIASES BBS_PROJECT_TARGET_TYPE_ALIASES
#define PROJECT_LANG_ALIASES BBS_PROJECT_LANG_ALIASES
#define PROJECT_STDLIB_ALIASES BBS_PROJECT_STDLIB_ALIASES
#define PROJECT_WARNING_LEVEL_ALIASES BBS_PROJECT_WARNING_LEVEL_ALIASES
#define PROJECT_OPT_LEVEL_ALIASES BBS_PROJECT_OPT_LEVEL_ALIASES
#define PROJECT_CMAKE_CONFIG_ALIASES BBS_PROJECT_CMAKE_CONFIG_ALIASES
#define PROJECT_LICENSE_ATTR_INFOS BBS_PROJECT_LICENSE_ATTR_INFOS
#define PROJECT_UNITY_ATTR_INFOS BBS_PROJECT_UNITY_ATTR_INFOS
#define PROJECT_TARGET_META_ATTR_INFOS BBS_PROJECT_TARGET_META_ATTR_INFOS
#define PROJECT_TARGET_ATTR_INFOS BBS_PROJECT_TARGET_ATTR_INFOS
#define PROJECT_PROJECT_ATTR_INFOS BBS_PROJECT_PROJECT_ATTR_INFOS

static inline const char** target_hook_cmds(const target* tgt, target_hook_kind kind) {
  return bbs_target_hook_cmds(tgt, kind);
}

static inline int target_hook_cmd_count(const target* tgt, target_hook_kind kind) {
  return bbs_target_hook_cmd_count(tgt, kind);
}
